### ISSUE TITLE
Python executables/shebang

### ISSUE THREAD

**Issue by natestemen** [XanaduAI/QHack2022#8]
While completing the challenges I noticed some of the python files have a `#!` (shebang) line at the top to make them runnable from the command line. E.g. this [file](https://github.com/XanaduAI/QHack/blob/475666469c3dff6de777def71a69bc7ce1947c0d/Coding_Challenges/algorithms_200_AdaptingTopology_template/adapting_topology_template.py) begins with `#! /usr/bin/python3`. As far as I know, a more appropriate (and portable) shebang is `#!/usr/bin/env python3` as `env` is always in `/usr/bin`, but `python` isn't in that location on everyone's machines. Indeed running `./order_matters_template.py < 1.in` fails for me. More details can be found at this [stack exchange answer](https://stackoverflow.com/a/19305076).

Lastly, since the shebang is included in many files, I would expect them to be executable, however all the ones I've tested are not.

If this is something worthy of fixing, I can open a PR. Let me know what you think.

**Comment by co9olguy** [comment]
Thanks @natestemen for noticing this :slightly_smiling_face:.

We anticipate users running the templates by invoking Python directly (and this is how we steer people in the documentation). As such, I believe the shebangs were put in there purely as a convenient hint. They were not a direct part of our testing, but thanks for catching that!

I'd say this is a minor inconsistency, and updating the questions requires a bit more than a PR to this repo (since we are mirroring the questions on the service that runs the challenges online). Thanks for the offer though :slightly_smiling_face:
